import Head from "next/head";
import { useState } from "react";
import AppLayout from "../components/AppLayout";
import Button from "../components/AppLayout/Button";
import GitHub from "../components/Icons/GitHub";
import { colors } from "../styles/theme";

import { loginWithGitHub } from "../firebase/client";

export default function Home() {
  const [user, setUser] = useState(null);
  const handleClick = () => {
    loginWithGitHub()
      .then((user) => {
        const { avatar, username, url } = user;
        setUser(user);
      })
      .catch((err) => console.log(err));
  };
  return (
    <>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" type="image/ico" />
      </Head>

      <AppLayout>
        <section>
          <img src="/devter-logo.png" alt="Logo" />
          <h1>Devter</h1>
          <h2>
            Talk about development
            <br />
            with developers
          </h2>
          <div>
            {user === null && (
              <Button onClick={handleClick}>
                <GitHub width={24} height={24} fill={"#fff"} />
                Login with GitHub
              </Button>
            )}
          </div>
        </section>
      </AppLayout>

      <style jsx>{`
        img {
          width: 120px;
        }

        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }

        h1 {
          font-weight: 600;
          margin-bottom: 16px;
          color: ${colors.secondary};
        }

        h2 {
          color: ${colors.primary};
          font-size: 21px;
          margin: 0;
        }

        div {
          margin-top: 16px;
        }
      `}</style>
    </>
  );
}
