import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <style jsx>{`
        h1 {
          text-align: center;
          font-size: 48px;
        }

        a {
          color: #09f;
          text-decoration: none;
        }
      `}</style>
    </div>
  );
}
